before_install: sudo apt-get install cmake
language: cpp
compiler:
  - gcc
  - clang
script: cmake . && make
notifications:
  recipients:
    - baptiste.lepilleur@gmail.com
  email:
    on_success: change
    on_failure: always
